Still has issues.
  File "/my/src/tonkadur-python-engine/tonkadur.py", line 266, in run
    result["content"] = self.compute(instruction['content'])
  File "/my/src/tonkadur-python-engine/tonkadur.py", line 78, in compute
    result['content'].append(self.compute(c))
  File "/my/src/tonkadur-python-engine/tonkadur.py", line 176, in compute
    result['content'].append(self.compute(c))
  File "/my/src/tonkadur-python-engine/tonkadur.py", line 176, in compute
    result['content'].append(self.compute(c))
  File "/my/src/tonkadur-python-engine/tonkadur.py", line 203, in compute
    target = target[addr]
TypeError: list indices must be integers or slices, not str

I assume that somewhere, an address is being used instead of the value.